# Generated by Django 5.0.4 on 2026-05-31 21:11

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ventanilla', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Terminal Central', max_length=100)),
                ('cantidad_plataformas', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name_plural': 'Terminales',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_oficial', models.CharField(max_length=200, unique=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('ENCARGADO', 'Encargado de Sucursal'), ('VENTANILLA', 'Empleado de Ventanilla')], default='VENTANILLA', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='viajes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefono', models.CharField(help_text='Número para notificaciones', max_length=20, unique=True)),
                ('recibir_alertas', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_pasajero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='viajes.terminal'),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horario_embarcacion', models.TimeField()),
                ('duracion', models.DurationField(help_text='Duración total del viaje completo')),
                ('dias_operativos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=15), blank=True, null=True, size=None)),
                ('plataformas_asignadas', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
                ('estado', models.CharField(choices=[('A_TIEMPO', 'A tiempo'), ('ABORDANDO', 'Abordando'), ('DEMORADO', 'Demorado'), ('FINALIZADO', 'Finalizado')], default='A_TIEMPO', max_length=20)),
                ('demora', models.DurationField(default=datetime.timedelta(0))),
                ('motivo_demora', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='viajes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField()),
                ('tiempo_desde_salida', models.DurationField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viajes.ubicacion')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='viajes.viaje')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
