# Generated by Django 5.2.7 on 2026-05-10 02:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ventanilla', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Terminal Central', max_length=100)),
                ('cantidad_plataformas', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name_plural': 'Terminales',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ENCARGADO', 'Encargado de Sucursal'), ('VENTANILLA', 'Empleado de Ventanilla')], default='VENTANILLA', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='viajes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Número para notificaciones', max_length=20, unique=True)),
                ('recibir_alertas', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_pasajero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('horario_embarcacion', models.TimeField()),
                ('duracion', models.DurationField(help_text='Formato: HH:MM:SS')),
                ('plataformas_asignadas', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('A_TIEMPO', 'A tiempo'), ('ABORDANDO', 'Abordando'), ('DEMORADO', 'Demorado')], default='A_TIEMPO', max_length=20)),
                ('demora', models.DurationField(default=datetime.timedelta(0))),
                ('motivo_demora', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='viajes.empresa')),
            ],
        ),
    ]
