# Generated by Django 5.0.4 on 2026-05-23 23:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='dias_operativos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=15), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='duracion',
            field=models.DurationField(help_text='Duración total del viaje completo'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='plataformas_asignadas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
