# Generated by Django 5.0.4 on 2026-05-31 21:35

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='demora',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='motivo_demora',
        ),
        migrations.CreateModel(
            name='EstadoViajeDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha en la que ocurre este registro')),
                ('estado', models.CharField(choices=[('A_TIEMPO', 'A tiempo'), ('ABORDANDO', 'Abordando'), ('DEMORADO', 'Demorado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='A_TIEMPO', max_length=20)),
                ('tiempo_demora', models.DurationField(default=datetime.timedelta(0))),
                ('motivo_demora', models.CharField(blank=True, max_length=255, null=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_diarios', to='viajes.viaje')),
            ],
            options={
                'unique_together': {('viaje', 'fecha')},
            },
        ),
    ]
